name: Development Workflow

on: [push]

jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Set up Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install dependencies
        run: |
          npm i
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          PATH=~/.npm-global/bin:$PATH
          npm i -g firebase-tools
          npm run build
          npm run deploy
