name: Development Workflow

on: [push]

jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set up Node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install dependencies
        run: |
          npm i
          npm run build
          npm run deploy
